### ISSUE TITLE
HashiCorp Vault Provider needs to identify to Vault as the pod it is servicing.

### ISSUE THREAD

**Issue by ritazh** [hashicorp/secrets-store-csi-driver-provider-vault#16]
Ref: https://github.com/deislabs/secrets-store-csi-driver/issues/59

**Comment by tam7t** [comment]
https://github.com/kubernetes/kubernetes/issues/86448 is a good upstream issue related to this.

In the meantime a possible solution would be for the cluster owner to add the addition RBAC binding to the CSI Driver service account `secrets-store-csi-driver`:

```yaml
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
```

With that permission, the vault node plugin would have the permissions to call the K8S API to obtain a service account token for the pod:

```
clientset.CoreV1().ServiceAccounts(namespace).CreateToken(name, req)
```

The volume mount context parameters
`csi.storage.k8s.io/pod.name` and `csi.storage.k8s.io/pod.namespace` are already passed to the Azure provider for Pod Identity.

`csi.storage.k8s.io/pod.uid` and `csi.storage.k8s.io/serviceAccount.name` would be needed in order to call `CreateToken`.

Once the driver is able to obtain service account tokens of the pod then direct auth using https://www.vaultproject.io/api-docs/auth/kubernetes/ would be possible.
