### ISSUE TITLE
Update version in documentation

### ISSUE THREAD

**Issue by rafis** [hashicorp/secrets-store-csi-driver-provider-vault#55]
Please update version of CSI Vault Driver Provider in your official documentation:
https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver#install-the-provider-vault-executable

Reason: Version 0.0.4 supports only K/V v1, but many people use K/V v2. People tend to use official documentation as installation instructions as opposed to reading README.md in Git repository.

**Comment by tomhjp** [comment]
Thanks for raising this! I've updated that page now. Given the breaking change in 0.0.5, there were two other tweaks to take care to notice - the SecretProviderClass now specifies the full path to the KV secret (v1/secret/db-pass) and the secret is written to a file named as the ObjectName (password) instead of the ObjectPath (v1/secret/db-pass).
